### ISSUE TITLE
what's this mean?

### ISSUE THREAD

**Issue by asgab** [neokoenig/RoomBooking#46]
Railo 4.2.1.008 Error (expression)
Message	invalid component definition, can't find component [roombooking.plugins.flashwrapper.flashwrapper]
Stacktrace	The Error Occurred in
/opt/railo/tomcat/webapps/roombooking/wheels/Plugins.cfc: line 125 
123: <cfset loc.wheelsVersion = SpanExcluding(variables.$class.wheelsVersion, " ")>
124: <cfloop collection="#loc.plugins#" item="loc.iPlugins">
125: <cfset loc.plugin = createobject("component", $componentPathToPlugin(loc.iPlugins)).init()>
126: <cfif not StructKeyExists(loc.plugin, "version") OR ListFind(loc.plugin.version, loc.wheelsVersion) OR variables.$class.loadIncompatiblePlugins>
127: <cfset variables.$class.plugins[loc.iPlugins] = loc.plugin>

called from /opt/railo/tomcat/webapps/roombooking/wheels/Plugins.cfc: line 30 
called from /opt/railo/tomcat/webapps/roombooking/root.cfm: line 1 
called from /opt/railo/tomcat/webapps/roombooking/wheels/global/internal.cfm: line 561 
called from /opt/railo/tomcat/webapps/roombooking/wheels/global/internal.cfm: line 968 
called from /opt/railo/tomcat/webapps/roombooking/wheels/events/onapplicationstart.cfm: line 376

**Comment by neokoenig** [comment]
It can’t find the flashwrapper plugin; try renaming /plugins/Flashwrapper/FlashWrapper.cfc to be all lowercase. (this is fixed in 1.2.1) - https://github.com/neokoenig/RoomBooking/releases/download/1.2/RoomBooking-1-2-1.zip

**Comment by abhijit13** [comment]
issue persists with 1.2.1 as well. 

invalid component definition, can't find component [railoserver.roombooking.plugins.flashwrapper.flashwrapper]

The Error Occurred in
/opt/railo-4.2.1.008-6/apache-tomcat/webapps/railoserver/roombooking/wheels/Plugins.cfc: line 125

    123: <cfset loc.wheelsVersion = SpanExcluding(variables.$class.wheelsVersion, " ")>
    124: <cfloop collection="#loc.plugins#" item="loc.iPlugins">
    125: <cfset loc.plugin = createobject("component", $componentPathToPlugin(loc.iPlugins)).init()>
    126: <cfif not StructKeyExists(loc.plugin, "version") OR ListFind(loc.plugin.version, loc.wheelsVersion) OR variables.$class.loadIncompatiblePlugins>
    127: <cfset variables.$class.plugins[loc.iPlugins] = loc.plugin>

called from /opt/railo-4.2.1.008-6/apache-tomcat/webapps/railoserver/roombooking/wheels/Plugins.cfc: line 30
called from /opt/railo-4.2.1.008-6/apache-tomcat/webapps/railoserver/roombooking/root.cfm: line 1
called from /opt/railo-4.2.1.008-6/apache-tomcat/webapps/railoserver/roombooking/wheels/global/internal.cfm: line 561
called from /opt/railo-4.2.1.008-6/apache-tomcat/webapps/railoserver/roombooking/wheels/global/internal.cfm: line 968
called from /opt/railo-4.2.1.008-6/apache-tomcat/webapps/railoserver/roombooking/wheels/events/onapplicationstart.cfm: line 376

**Comment by neokoenig** [comment]
It's a case sensitivity issue with the plugin; in `/plugins/` make sure there's folder called `/flashwrapper/` with `flashwrapper.cfc` (all lowercase) in; you might need to do the same with shortcodes too.

**Comment by zhakid** [comment]
the folder is all lowercase and the issue persist

**Comment by neokoenig** [comment]
@zhakid could you check this thread - https://github.com/neokoenig/RoomBooking/issues/68 and confirm?

**Comment by zhakid** [comment]
drwxr-xr-x 4 root root 4096 Dec 28 15:37 .
drwxr-xr-x 4 root root 4096 Dec 28 15:36 ..
-rw-r--r-- 1 root root  203 May 28  2013 FlashWrapper.cfc
drwxr-xr-x 2 root root 4096 May 28  2013 controller
-rw-r--r-- 1 root root  203 May 28  2013 flashWrapper.cfc
-rw-r--r-- 1 root root 3967 Apr  3  2012 index.cfm
drwxr-xr-x 2 root root 4096 May 28  2013 stylesheets

**Comment by neokoenig** [comment]
so `flashWrapper` or `FlashWrapper` needs to be `flashwrapper.cfc`
Note: All lowercase.

**Comment by zhakid** [comment]
drwxr-xr-x 4 root root 4096 Dec 28 15:47 .
drwxr-xr-x 4 root root 4096 Dec 28 15:36 ..
-rw-r--r-- 1 root root  203 May 28  2013 FlashWrapper.cfc (This one is created each time i reload the page)
drwxr-xr-x 2 root root 4096 May 28  2013 controller
-rw-r--r-- 1 root root  203 May 28  2013 flashwrapper.cfc
-rw-r--r-- 1 root root 3967 Apr  3  2012 index.cfm
drwxr-xr-x 2 root root 4096 May 28  2013 stylesheets

**Comment by neokoenig** [comment]
... are you running this in a subdirectory? i.e, `127.0.0.0/conference/` ?
If so, that might be it. I've not tested it in a subdir...

**Comment by zhakid** [comment]
Thanks men that solved the problem, cant be install on subdirectory
